/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mp2srt.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-26-2013
 * 
 * XDoclet definition:
 * @struts.form name="setcsvForm"
 */
public class SetcsvForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** csvfile property */
	private String csvfile;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the csvfile.
	 * @return String
	 */
	public String getCsvfile() {
		return csvfile;
	}

	/** 
	 * Set the csvfile.
	 * @param csvfile The csvfile to set
	 */
	public void setCsvfile(String csvfile) {
		this.csvfile = csvfile;
	}
}