/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mp2srt.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mp2srt.hibernate.Bts;
import com.mp2srt.hibernate.BtsDAO;
import com.mp2srt.struts.form.GetbtsForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-26-2013
 * 
 * XDoclet definition:
 * @struts.action path="/getbts" name="getbtsForm" input="/map.jsp" scope="request" validate="true"
 * @struts.action-forward name="get" path="/map.jsp"
 */
public class GetbtsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GetbtsForm getbtsForm = (GetbtsForm) form;// TODO Auto-generated method stub
		
		
		BtsDAO btsdao = new BtsDAO();
		
		long j = 1;
		Bts bts = btsdao.findById(j);
		
		//List<Bts> listvocab = new ArrayList<Bts>(); 
		//listvocab = btsdao.findAll();
		
		request.getSession().setAttribute("nombts",bts.getNomBts());
		request.getSession().setAttribute("location",bts.getLangitude() + "," + bts.getLatitude());
		request.getSession().setAttribute("puissance",bts.getPuissance());
		request.getSession().setAttribute("info",bts.getInfo());
		j++;
		
		//request.getSession().setAttribute("btslist", "36.822074,10.178778");
		
		return mapping.findForward("get");
	}
}